### Feature Engineering

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')


je_data = pd.read_csv('PROCESSED_GL_DATA_ALL.csv')

In [2]:
je_data.sample(3).T

                          85361           190008         193033
LIBDIARIOID                48361          135726         139592
ENTERPRISEID                 348              24            328
ENTEPRISENAME        Entity_0348     Entity_0024    Entity_0328
PROPERTYID                     0              95              0
LIBDIATYPEID                   6               5              5
YEARID                      2022            2024           2024
MONTHID                       10               5              2
SOURCEID                       1               0              0
ODATAID                      826               0              0
COACODDETAIL              380101          500203         101001
DESCTYPE           Balance Sheet   Balance Sheet  Balance Sheet
DESCSUBTYPE               Assets          Equity         Assets
COANAME             Other Assets           Draws           Bank
DEBIT                        0.0          5400.0        11800.0
CREDIT                   5015.96             0.0            0.0
NET                     -5015.96          5400.0        11800.0
LOCATION                     NaN   IL-Belleville            NaN
STATE                        NaN        Illinois            NaN
CITY                         NaN      Belleville            NaN
STATEID                      NaN              IL            NaN
DESC_TYPENN                  NaN              NN            NaN
DESC_TYPEPROPERTY            NaN             LJL            NaN
MJ_OWNER                     NaN  Client_0040 **            NaN
OPT_LEASE                    NaN           Y (1)            NaN
CAPRATE                      NaN             7.9            NaN
TENANTID                     NaN             3.0            NaN
TENANTNAME                   NaN     Tenant_0003            NaN
DESC_TYPEMGMT                NaN      Fin & Prop            NaN
PORTFOLIOID                  NaN             1.0            NaN
PORTFOLIONAME                NaN          L2-ALL            NaN
ADMIN_ENTITYID               NaN             6.0            NaN
ADMIN_ENTITY                 NaN         AE_0006            NaN
DESC_TYPETENANT              NaN   SINGLE TENANT            NaN
DESC_CATEGORY                NaN        PHARMACY            NaN

In [3]:
#Fill categorical
print("La forma del préstamo_demográfico es {}".format(je_data.shape))
je_data.isna().sum()

La forma del préstamo_demográfico es (293974, 34)

LIBDIARIOID              0
ENTERPRISEID             0
ENTEPRISENAME            0
PROPERTYID               0
LIBDIATYPEID             0
YEARID                   0
MONTHID                  0
SOURCEID                 0
ODATAID                  0
COACODDETAIL             0
DESCTYPE                 0
DESCSUBTYPE              0
COANAME                  0
DEBIT                   17
CREDIT                  16
NET                     18
LOCATION             48995
STATE                48995
CITY                 48995
STATEID              48995
DESC_TYPENN          48995
DESC_TYPEPROPERTY    48995
MJ_OWNER             48995
OPT_LEASE            91424
CAPRATE              49460
TENANTID             49460
TENANTNAME           49460
DESC_TYPEMGMT        48995
PORTFOLIOID          48995
PORTFOLIONAME        48995
ADMIN_ENTITYID       49760
ADMIN_ENTITY         49760
DESC_TYPETENANT      48995
DESC_CATEGORY        48995
dtype: int64

In [4]:
je_data['PORTFOLIONAME'].value_counts()

PORTFOLIONAME
L2-ALL    166666
L2B        75895
LJL         2075
3RD          343
Name: count, dtype: int64

In [5]:
#fill with mode (Permanent)
je_data['PORTFOLIONAME'] = je_data['PORTFOLIONAME'].fillna(value='L2-ALL')
je_data.isna().sum()

LIBDIARIOID              0
ENTERPRISEID             0
ENTEPRISENAME            0
PROPERTYID               0
LIBDIATYPEID             0
YEARID                   0
MONTHID                  0
SOURCEID                 0
ODATAID                  0
COACODDETAIL             0
DESCTYPE                 0
DESCSUBTYPE              0
COANAME                  0
DEBIT                   17
CREDIT                  16
NET                     18
LOCATION             48995
STATE                48995
CITY                 48995
STATEID              48995
DESC_TYPENN          48995
DESC_TYPEPROPERTY    48995
MJ_OWNER             48995
OPT_LEASE            91424
CAPRATE              49460
TENANTID             49460
TENANTNAME           49460
DESC_TYPEMGMT        48995
PORTFOLIOID          48995
PORTFOLIONAME            0
ADMIN_ENTITYID       49760
ADMIN_ENTITY         49760
DESC_TYPETENANT      48995
DESC_CATEGORY        48995
dtype: int64

In [6]:
je_data['CAPRATE'].value_counts()

CAPRATE
7.383    15386
7.652     8467
8.141     8054
7.417     6272
9.061     5934
         ...
8.249       26
6.782       14
6.617       14
6.845       10
6.660        6
Name: count, Length: 230, dtype: int64

In [7]:
#fill with mode (Permanent)
je_data['CAPRATE'] = je_data['CAPRATE'].fillna(value='7')
je_data.isna().sum()

LIBDIARIOID              0
ENTERPRISEID             0
ENTEPRISENAME            0
PROPERTYID               0
LIBDIATYPEID             0
YEARID                   0
MONTHID                  0
SOURCEID                 0
ODATAID                  0
COACODDETAIL             0
DESCTYPE                 0
DESCSUBTYPE              0
COANAME                  0
DEBIT                   17
CREDIT                  16
NET                     18
LOCATION             48995
STATE                48995
CITY                 48995
STATEID              48995
DESC_TYPENN          48995
DESC_TYPEPROPERTY    48995
MJ_OWNER             48995
OPT_LEASE            91424
CAPRATE                  0
TENANTID             49460
TENANTNAME           49460
DESC_TYPEMGMT        48995
PORTFOLIOID          48995
PORTFOLIONAME            0
ADMIN_ENTITYID       49760
ADMIN_ENTITY         49760
DESC_TYPETENANT      48995
DESC_CATEGORY        48995
dtype: int64

In [8]:
je_data['ADMIN_ENTITYID'].value_counts()

ADMIN_ENTITYID
6.0      138724
338.0     84533
400.0     20957
Name: count, dtype: int64

In [9]:
#fill with mode (Permanent)
je_data['ADMIN_ENTITYID'] = je_data['ADMIN_ENTITYID'].fillna(value='6')
je_data.isna().sum()

LIBDIARIOID              0
ENTERPRISEID             0
ENTEPRISENAME            0
PROPERTYID               0
LIBDIATYPEID             0
YEARID                   0
MONTHID                  0
SOURCEID                 0
ODATAID                  0
COACODDETAIL             0
DESCTYPE                 0
DESCSUBTYPE              0
COANAME                  0
DEBIT                   17
CREDIT                  16
NET                     18
LOCATION             48995
STATE                48995
CITY                 48995
STATEID              48995
DESC_TYPENN          48995
DESC_TYPEPROPERTY    48995
MJ_OWNER             48995
OPT_LEASE            91424
CAPRATE                  0
TENANTID             49460
TENANTNAME           49460
DESC_TYPEMGMT        48995
PORTFOLIOID          48995
PORTFOLIONAME            0
ADMIN_ENTITYID           0
ADMIN_ENTITY         49760
DESC_TYPETENANT      48995
DESC_CATEGORY        48995
dtype: int64

In [10]:
je_data['ENTERPRISEID'].value_counts()

ENTERPRISEID
6      20882
370    14077
357     8303
374     8020
404     7936
       ...
468       29
471       28
469       24
149       20
172       20
Name: count, Length: 244, dtype: int64

In [11]:
#fill with mode (Permanent)
je_data['ENTERPRISEID'] = je_data['ENTERPRISEID'].fillna(value='6')
je_data.isna().sum()

LIBDIARIOID              0
ENTERPRISEID             0
ENTEPRISENAME            0
PROPERTYID               0
LIBDIATYPEID             0
YEARID                   0
MONTHID                  0
SOURCEID                 0
ODATAID                  0
COACODDETAIL             0
DESCTYPE                 0
DESCSUBTYPE              0
COANAME                  0
DEBIT                   17
CREDIT                  16
NET                     18
LOCATION             48995
STATE                48995
CITY                 48995
STATEID              48995
DESC_TYPENN          48995
DESC_TYPEPROPERTY    48995
MJ_OWNER             48995
OPT_LEASE            91424
CAPRATE                  0
TENANTID             49460
TENANTNAME           49460
DESC_TYPEMGMT        48995
PORTFOLIOID          48995
PORTFOLIONAME            0
ADMIN_ENTITYID           0
ADMIN_ENTITY         49760
DESC_TYPETENANT      48995
DESC_CATEGORY        48995
dtype: int64

In [12]:
je_data.isna().sum()

LIBDIARIOID              0
ENTERPRISEID             0
ENTEPRISENAME            0
PROPERTYID               0
LIBDIATYPEID             0
YEARID                   0
MONTHID                  0
SOURCEID                 0
ODATAID                  0
COACODDETAIL             0
DESCTYPE                 0
DESCSUBTYPE              0
COANAME                  0
DEBIT                   17
CREDIT                  16
NET                     18
LOCATION             48995
STATE                48995
CITY                 48995
STATEID              48995
DESC_TYPENN          48995
DESC_TYPEPROPERTY    48995
MJ_OWNER             48995
OPT_LEASE            91424
CAPRATE                  0
TENANTID             49460
TENANTNAME           49460
DESC_TYPEMGMT        48995
PORTFOLIOID          48995
PORTFOLIONAME            0
ADMIN_ENTITYID           0
ADMIN_ENTITY         49760
DESC_TYPETENANT      48995
DESC_CATEGORY        48995
dtype: int64

In [13]:
mean_df = round(je_data['CAPRATE'].mean())
mode_df = round(je_data['CAPRATE'].mode()[0])
median_df = round(je_data['CAPRATE'].median())

#Fill with mean
print("CAPRATE with mean value of {}".format(mean_df))
je_data['CAPRATE'] = je_data['CAPRATE'].fillna(mean_df)

#Fill with mode
print("CAPRATE with modal value of {}".format(mode_df))
je_data['CAPRATE'] = je_data['CAPRATE'].fillna(mode_df)

#Fill with median
print("CAPRATE with median value of {}".format(median_df))
je_data['CAPRATE'] = je_data['CAPRATE'].fillna(median_df)

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [ ]:
#get correlated values
plt.figure(figsize = (15,10))
# Calculate correlation only for numeric columns
sns.heatmap(je_data.corr(numeric_only=True))
plt.show() # Remember to show the plot

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

to_train = ['PORTFOLIOID', 'CAPRATE','ADMIN_ENTITYID', 'ENTERPRISEID' ]

temp_df = je_data[to_train]
#Step-1: Split the dataset that contains the missing values and no missing values as test and train respectively.
x_train = temp_df[temp_df['PORTFOLIOID'].notnull()].drop(columns='PORTFOLIOID')
y_train = temp_df[temp_df['PORTFOLIOID'].notnull()]['PORTFOLIOID']
x_test = temp_df[temp_df['PORTFOLIOID'].isnull()].drop(columns='PORTFOLIOID')


lr.fit(x_train, y_train)
pred = lr.predict(x_test)

print(np.round(pred, 5))

je_data['PORTFOLIOID'][je_data['PORTFOLIOID'].isnull()] = pred

In [14]:
#get the index of missing so we can some of the values used for filling
missing_indx = list(je_data['PORTFOLIOID'][je_data['PORTFOLIOID'].isna()].index)

In [15]:
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer  
from sklearn.impute import IterativeImputer

from sklearn.ensemble import RandomForestRegressor

# Run imputer with a Random Forest estimator
imp = IterativeImputer(RandomForestRegressor(n_estimators=5), max_iter=5, random_state=1)

to_train = ['PORTFOLIOID', 'CAPRATE','ADMIN_ENTITYID', 'ENTERPRISEID']
je_data[to_train] = pd.DataFrame(imp.fit_transform(je_data[to_train]), columns=to_train)

In [16]:
je_data['PORTFOLIOID'][missing_indx].head(10)

8      1.0
9      1.0
64     1.0
65     1.0
82     1.0
83     1.0
84     1.0
85     1.0
118    1.0
119    1.0
Name: PORTFOLIOID, dtype: float64

In [17]:
#The feature level_of_education is ordinal
je_data['PORTFOLIONAME'].unique()

array(['L2-ALL', 'L2B', '3RD', 'LJL'], dtype=object)

In [18]:
#use a simple map function
map_education = {"L2-ALL" : 1, "L2B": 2, "3RD": 3, "LJL": 4}
    
je_data['Portfolio_Entity'] = je_data['PORTFOLIONAME'].map(map_education)

je_data['Portfolio_Entity'].value_counts()

Portfolio_Entity
1    215661
2     75895
4      2075
3       343
Name: count, dtype: int64

----------------------------------------------------------------------------------------------------------------------

In [19]:
#Check the number of unique classes
cat_cols = je_data.select_dtypes(include='object').columns

for col in cat_cols:
    print("Number of classes in {}".format(col))
    print(je_data[col].nunique())
    print('--------------------------')

Number of classes in ENTEPRISENAME
244
--------------------------
Number of classes in DESCTYPE
2
--------------------------
Number of classes in DESCSUBTYPE
5
--------------------------
Number of classes in COANAME
63
--------------------------
Number of classes in LOCATION
246
--------------------------
Number of classes in STATE
38
--------------------------
Number of classes in CITY
243
--------------------------
Number of classes in STATEID
38
--------------------------
Number of classes in DESC_TYPENN
2
--------------------------
Number of classes in DESC_TYPEPROPERTY
4
--------------------------
Number of classes in MJ_OWNER
57
--------------------------
Number of classes in OPT_LEASE
4
--------------------------
Number of classes in TENANTNAME
40
--------------------------
Number of classes in DESC_TYPEMGMT
4
--------------------------
Number of classes in PORTFOLIONAME
4
--------------------------
Number of classes in ADMIN_ENTITY
3
--------------------------
Number of classes in DESC_TYPETENANT
2
--------------------------
Number of classes in DESC_CATEGORY
2
--------------------------

La función OrdinalEncoder de la biblioteca categorical_encoders se puede utilizar para etiquetar y codificar como se muestra a continuación:

In [20]:
pip install category_encoders

Requirement already satisfied: category_encoders in c:\users\diego\anaconda3b\lib\site-packages (2.8.1)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.14.0 in c:\users\diego\anaconda3b\lib\site-packages (from category_encoders) (1.26.4)
Requirement already satisfied: pandas>=1.0.5 in c:\users\diego\anaconda3b\lib\site-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in c:\users\diego\anaconda3b\lib\site-packages (from category_encoders) (0.5.6)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\diego\anaconda3b\lib\site-packages (from category_encoders) (1.7.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\diego\anaconda3b\lib\site-packages (from category_encoders) (1.13.1)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\diego\anaconda3b\lib\site-packages (from category_encoders) (0.14.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\diego\anaconda3b\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\diego\anaconda3b\lib\site-packages (from pandas>=1.0.5->category_encoders) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\diego\anaconda3b\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3)
Requirement already satisfied: six in c:\users\diego\anaconda3b\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\diego\anaconda3b\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\diego\anaconda3b\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in c:\users\diego\anaconda3b\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (24.1)

In [21]:
pip install scikit-learn<1.2

Note: you may need to restart the kernel to use updated packages.

El sistema no puede encontrar el archivo especificado.

In [22]:
import category_encoders as ce

#Label encoding
cat_cols = ['ENTEPRISENAME', 'PORTFOLIONAME'] 

encoder = ce.OrdinalEncoder(cols=cat_cols)
je_data = encoder.fit_transform(je_data)

In [23]:
je_data.head().T

,0,1,2,3,4
LIBDIARIOID,1,1,2,2,3
ENTERPRISEID,2.0,2.0,3.0,3.0,7.0
ENTEPRISENAME,1,1,2,2,3
PROPERTYID,85,85,87,87,102
LIBDIATYPEID,2,2,2,2,2
YEARID,2020,2020,2020,2020,2020
MONTHID,1,1,1,1,1
SOURCEID,2,2,2,2,2
ODATAID,3,3,3,3,1
COACODDETAIL,101001,700101,101001,700101,101001
DESCTYPE,Balance Sheet,Profit & Loss,Balance Sheet,Profit & Loss,Balance Sheet
DESCSUBTYPE,Assets,Income,Assets,Income,Assets
COANAME,Bank,Income,Bank,Income,Bank
DEBIT,29250.0,0.0,27775.25,0.0,27856.24
CREDIT,0.0,29250.0,0.0,27775.25,0.0
NET,29250.0,-29250.0,27775.25,-27775.25,27856.24
LOCATION,IA-Cedar Rapids,IA-Cedar Rapids,OH-Boardman,OH-Boardman,MO-Belton
STATE,Iowa,Iowa,Ohio,Ohio,Missouri
CITY,Cedar Rapids,Cedar Rapids,Boardman,Boardman,Belton
STATEID,IA,IA,OH,OH,MO
DESC_TYPENN,NN,NN,NN,NN,NNN
DESC_TYPEPROPERTY,LJL,LJL,LJL,LJL,L2
MJ_OWNER,Client_0001 **,Client_0001 **,Client_0001 **,Client_0001 **,Client_0001 **
OPT_LEASE,Y (3),Y (3),Y (3),Y (3),Y (3)
CAPRATE,8.375,8.375,8.42,8.42,7.865
TENANTID,3.0,3.0,3.0,3.0,1.0
TENANTNAME,Tenant_0003,Tenant_0003,Tenant_0003,Tenant_0003,Tenant_0001
DESC_TYPEMGMT,Fin & Prop,Fin & Prop,Fin & Prop,Fin & Prop,Fin & Prop
PORTFOLIOID,1.0,1.0,1.0,1.0,1.0
PORTFOLIONAME,1,1,1,1,1
ADMIN_ENTITYID,6.0,6.0,6.0,6.0,6.0
ADMIN_ENTITY,AE_0006,AE_0006,AE_0006,AE_0006,AE_0006
DESC_TYPETENANT,SINGLE TENANT,SINGLE TENANT,SINGLE TENANT,SINGLE TENANT,SINGLE TENANT
DESC_CATEGORY,PHARMACY,PHARMACY,PHARMACY,PHARMACY,PHARMACY
Portfolio_Entity,1,1,1,1,1

In [24]:
cats = [ 'PORTFOLIONAME','ENTEPRISENAME']

one_hot_enc = ce.OneHotEncoder(cols=cats)
je_data = one_hot_enc.fit_transform(je_data)

In [25]:
je_data.head().T

,0,1,2,3,4
LIBDIARIOID,1,1,2,2,3
ENTERPRISEID,2.0,2.0,3.0,3.0,7.0
ENTEPRISENAME_1,1,1,0,0,0
ENTEPRISENAME_2,0,0,1,1,0
ENTEPRISENAME_3,0,0,0,0,1
...,...,...,...,...,...
ADMIN_ENTITYID,6.0,6.0,6.0,6.0,6.0
ADMIN_ENTITY,AE_0006,AE_0006,AE_0006,AE_0006,AE_0006
DESC_TYPETENANT,SINGLE TENANT,SINGLE TENANT,SINGLE TENANT,SINGLE TENANT,SINGLE TENANT
DESC_CATEGORY,PHARMACY,PHARMACY,PHARMACY,PHARMACY,PHARMACY
Portfolio_Entity,1,1,1,1,1

__Codificación Hash:__ La codificación hash, o hash de características, es una forma rápida y eficiente de codificar características. Es muy eficiente para características categóricas con un gran número de clases. El codificador hash funciona aplicando una función hash a las características.

In [26]:
cat_cols = ['PORTFOLIONAME','ENTEPRISENAME'] 

hash_enc = ce.HashingEncoder(cols=cat_cols, n_components=10)
je_data = hash_enc.fit_transform(je_data)

je_data.head().T

ValueError: X does not contain the columns listed in cols

In [ ]:
sns.distplot(je_data['PORTFOLIOID'])
plt.title("Histogram of PORTFOLIOID")
plt.show()

In [ ]:
je_data['Distance (KM)'] =  np.log1p(je_data['PORTFOLIOID'])
sns.distplot(je_data['PORTFOLIOID'])
plt.title("PORTFOLIOID)")
plt.savefig("hist_trans.png")
plt.show()

In [ ]:
#Create feature interest
je_data['NETV2'] = je_data['DEBIT'] - je_data['CREDIT']

In [ ]:
# Groupby customer id and calculate their total loans taken
loannumber_count = (
    je_data.groupby(by='PORTFOLIOID')['ENTERPRISEID']
    .count() # Use .count() directly, which returns a Series
    .reset_index(name='LIBDIARIOID') # Convert Series back to DataFrame and name the new column
)

# merge back to dataset on customer_id
je_data = je_data.merge(right=loannumber_count, how='left', on='PORTFOLIOID')

# Verifica el resultado
je_data.head().T

In [27]:
#create feature speed in sendy dataset
je_data['NETV3'] = je_data['DEBIT'] - je_data['CREDIT']
je_data.head().T

,0,1,2,3,4
LIBDIARIOID,1,1,2,2,3
ENTERPRISEID,2.0,2.0,3.0,3.0,7.0
ENTEPRISENAME_1,1,1,0,0,0
ENTEPRISENAME_2,0,0,1,1,0
ENTEPRISENAME_3,0,0,0,0,1
...,...,...,...,...,...
ADMIN_ENTITY,AE_0006,AE_0006,AE_0006,AE_0006,AE_0006
DESC_TYPETENANT,SINGLE TENANT,SINGLE TENANT,SINGLE TENANT,SINGLE TENANT,SINGLE TENANT
DESC_CATEGORY,PHARMACY,PHARMACY,PHARMACY,PHARMACY,PHARMACY
Portfolio_Entity,1,1,1,1,1
NETV3,29250.0,-29250.0,27775.25,-27775.25,27856.24

In [28]:
#Use Sklearn Polynomial Features
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures()
to_cross = ['YEARID', 'MONTHID', 'ADMIN_ENTITYID']
crossed_feats = poly.fit_transform(je_data[to_cross].values)

#Convert to Pandas DataFrame and merge to original dataset
crossed_feats = pd.DataFrame(crossed_feats)
je_data = pd.concat([je_data, crossed_feats], axis=1)

In [29]:
je_data.head().T

                       0        1        2        3        4
LIBDIARIOID            1        1        2        2        3
ENTERPRISEID         2.0      2.0      3.0      3.0      7.0
ENTEPRISENAME_1        1        1        0        0        0
ENTEPRISENAME_2        0        0        1        1        0
ENTEPRISENAME_3        0        0        0        0        1
...                  ...      ...      ...      ...      ...
5                 2020.0   2020.0   2020.0   2020.0   2020.0
6                12120.0  12120.0  12120.0  12120.0  12120.0
7                    1.0      1.0      1.0      1.0      1.0
8                    6.0      6.0      6.0      6.0      6.0
9                   36.0     36.0     36.0     36.0     36.0

[292 rows x 5 columns]

In [30]:
#Use standard scaler
from sklearn.preprocessing import StandardScaler

feats = ['YEARID', 'MONTHID', 'ADMIN_ENTITYID'] 
sc = StandardScaler()
sc_data = sc.fit_transform(je_data[feats])

In [31]:
sc_data

array([[-2.07509731, -1.36455681, -0.74512171],
       [-2.07509731, -1.36455681, -0.74512171],
       [-2.07509731, -1.36455681, -0.74512171],
       ...,
       [ 1.34130916,  0.00911658,  1.63096583],
       [ 1.34130916,  0.00911658,  1.63096583],
       [ 1.34130916,  0.00911658,  1.63096583]])

In [32]:
#Use Robust scaler
from sklearn.preprocessing import RobustScaler

robsc = RobustScaler()
rb_data = robsc.fit_transform(je_data[feats])

In [33]:
rb_data

array([[-1.5       , -0.83333333,  0.        ],
       [-1.5       , -0.83333333,  0.        ],
       [-1.5       , -0.83333333,  0.        ],
       ...,
       [ 1.        ,  0.        ,  1.18674699],
       [ 1.        ,  0.        ,  1.18674699],
       [ 1.        ,  0.        ,  1.18674699]])

In [34]:
#Use MinMaxScaler scaler

from sklearn.preprocessing import MinMaxScaler

minsc = MinMaxScaler(feature_range=(0,2))
minmax_data = minsc.fit_transform(je_data[feats])

In [35]:
minmax_data

array([[0.28571429, 0.        , 0.        ],
       [0.28571429, 0.        , 0.        ],
       [0.28571429, 0.        , 0.        ],
       ...,
       [1.71428571, 0.90909091, 2.        ],
       [1.71428571, 0.90909091, 2.        ],
       [1.71428571, 0.90909091, 2.        ]])

---------------------------------------------------------------------------------------------